### ISSUE TITLE
拖拽任意一个栏改变大小会报错

### ISSUE THREAD

**Issue by heart-xy** [ArisAgeha/picture-manager-viewer#2]
![QQ截图20200507100041](https://user-images.githubusercontent.com/20472126/81246340-e196f300-9049-11ea-85f9-6bebfea81d19.jpg)

**Comment by ArisAgeha** [comment]
忘记去掉测试代码了！！！
马上修复
稍等

**Comment by heart-xy** [comment]
> 忘记去掉测试代码了！！！
> 马上修复
> 稍等

顺便建议以后更新把快捷键说明内置下，总感觉看个设置还要到github上来就很反人类
![QQ图片20200507102922](https://user-images.githubusercontent.com/20472126/81247867-a5fe2800-904d-11ea-9e10-89040ba6cb17.jpg)

**Comment by ArisAgeha** [comment]
> > 忘记去掉测试代码了！！！
> > 马上修复
> > 稍等
> 
> 顺便建议以后更新把快捷键说明内置下，总感觉看个设置还要到github上来就很反人类
> ![QQ图片20200507102922](https://user-images.githubusercontent.com/20472126/81247867-a5fe2800-904d-11ea-9e10-89040ba6cb17.jpg)

修复了，请下载1.0.1版本 点击readme上的链接即可 或者到release里找
快捷键说明在日程表上了

其实UI和逻辑都已经构思好了
只是没时间做2333
这个可以说只是个预览版
跟我一开始构思的版本对比
大概只完成了40%左右的功能ORZ

（不过其实现在快捷键不多啦，用几下就记住了）
无非就是常用ctrl + [w/tab/滚轮]的各种组合
然后阅读模式下就是小键盘上的几个数字键来改变阅读方向和页数排列方式……

总之会加油做的2333
（在做了在做了.....0%.jpg）

**Comment by heart-xy** [comment]
> > > 忘记去掉测试代码了！！！
> > > 马上修复
> > > 稍等
> > 
> > 
> > 顺便建议以后更新把快捷键说明内置下，总感觉看个设置还要到github上来就很反人类
> > ![QQ图片20200507102922](https://user-images.githubusercontent.com/20472126/81247867-a5fe2800-904d-11ea-9e10-89040ba6cb17.jpg)
> 
> 修复了，请下载1.0.1版本 点击readme上的链接即可 或者到release里找
> 快捷键说明在日程表上了
> 
> 其实UI和逻辑都已经构思好了
> 只是没时间做2333
> 这个可以说只是个预览版
> 跟我一开始构思的版本对比
> 大概只完成了40%左右的功能ORZ
> 
> （不过其实现在快捷键不多啦，用几下就记住了）
> 无非就是常用ctrl + [w/tab/滚轮]的各种组合
> 然后阅读模式下就是小键盘上的几个数字键来改变阅读方向和页数排列方式……
> 
> 总之会加油做的2333
> （在做了在做了.....0%.jpg）

加油，还是挺好用、挺好看的

**Comment by ArisAgeha** [comment]
> > > > 忘记去掉测试代码了！！！
> > > > 马上修复
> > > > 稍等
> > > 
> > > 
> > > 顺便建议以后更新把快捷键说明内置下，总感觉看个设置还要到github上来就很反人类
> > > ![QQ图片20200507102922](https://user-images.githubusercontent.com/20472126/81247867-a5fe2800-904d-11ea-9e10-89040ba6cb17.jpg)
> > 
> > 
> > 修复了，请下载1.0.1版本 点击readme上的链接即可 或者到release里找
> > 快捷键说明在日程表上了
> > 其实UI和逻辑都已经构思好了
> > 只是没时间做2333
> > 这个可以说只是个预览版
> > 跟我一开始构思的版本对比
> > 大概只完成了40%左右的功能ORZ
> > （不过其实现在快捷键不多啦，用几下就记住了）
> > 无非就是常用ctrl + [w/tab/滚轮]的各种组合
> > 然后阅读模式下就是小键盘上的几个数字键来改变阅读方向和页数排列方式……
> > 总之会加油做的2333
> > （在做了在做了.....0%.jpg）
> 
> 加油，还是挺好用、挺好看的

感谢支持 ♪(･ω･)ﾉ
