### ISSUE TITLE
建议优化

### ISSUE THREAD

**Issue by cby2566** [ArisAgeha/picture-manager-viewer#3]
1，右侧下方设置 分类和阅读设置 和 左侧文件夹结构树 的区域，其显示隐藏的操作，是否可以增加一个按钮从而点击切换“显示/隐藏”。而不是通过拖动的方式实现“显示/隐藏”。
2，左侧的 四个图标按钮 是否可以增加一个hover显示“提示文本”气泡。
3，有些文件名比较长，左侧文件夹结构树hover时，能否显示完整名称的气泡，超过长度则换行。
4，已阅读过的文件夹，是否可以将页数显示在 左侧文件夹结构树 文件名的旁边。

**Comment by ArisAgeha** [comment]
抱歉这两天一直在看论坛、优化性能 
都忘了看issues了
npm那边发包导致好多邮件提醒 搞得也把github的issues提示邮件忽略掉了... 

1、2、3 可以有，下个版本应该会加入
4 需要考虑一下，可以显示页数，但是不一定会按照您说的那样显示
其实我想尽量避免添加一切必要的ui
因为本身走的就是简洁风
不想让不必要的UI抢占了视野
总之我会在衡量后进行优化的
谢谢反馈 ~

**Comment by ArisAgeha** [comment]
> 3，有些文件名比较长，左侧文件夹结构树hover时，能否显示完整名称的气泡，超过长度则换行。

对了换行是不会考虑的 
我曾经试过 整个目录树会很丑 
非常丑 相当臃肿 
应该还是会以气泡提示的形式来进行

顺带一提我当前进度是在做软件内置更新
这样以后就不用每次发release都要到处奔跑相告了
完成了这个之后就会开始做一下小的功能优化，包括您所反馈的。

**Comment by cby2566** [comment]
热更新好评
