### ISSUE TITLE
请问支持zip和pdf格式的漫画浏览吗？

### ISSUE THREAD

**Issue by Nigel-NI** [ArisAgeha/picture-manager-viewer#5]
我的漫画大多数都是zip和pdf格式的文件。我把漫画目录添加到软件里，但是软件似乎不显示。如果不支持的话，希望未来能进一步添加对以上两种格式文件阅读的支持，辛苦啦，非常感谢！

**Comment by ArisAgeha** [comment]
感谢您的反馈 这边确实也收到一些这种需求
pdf的话未来确定会提供支持
但是zip的话不一定（不在熟悉的领域，另外任务安排有点多，加上最近比较繁忙，多重因素下，因此在计划表全部完成前都不会作考虑）
所以比较抱歉啦

**Comment by Nigel-NI** [comment]
感谢开发大大及时回复。zip文件支持不着急，毕竟可以解压后再看。不过还是希望日后可以支持此功能。Star已点，希望开发大大再接再厉！
